;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;; Settings ;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(setq inhibit-startup-message t) ; Remove splash screen
(setq display-line-numbers 'relative) ; Relative window numbering
(global-display-line-numbers-mode 1) ; Show line numbers

;; Remove UI bloat
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;; Packages Setup ;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))
(package-initialize)
(unless package-archive-contents
    (package-refresh-contents))
(unless (package-installed-p 'use-package)
   (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;; Packages ;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(use-package counsel)

(use-package ivy
  :diminish
  :bind (("C-s" . swiperc)
         :map ivy-minibuffer-map
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)))
(ivy-mode 1) ; Enable ivy

(use-package evil)
(evil-mode 1)

(use-package general)

(use-package all-the-icons)

(use-package doom-modeline)
(doom-modeline-mode 1) 

(use-package doom-themes
  :ensure t
  :config
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  (load-theme 'doom-one t)
  (doom-themes-visual-bell-config)
  (doom-themes-neotree-config)
  (doom-themes-treemacs-config)
  (doom-themes-org-config))

(use-package neotree)

(use-package highlight-indent-guides)
(setq highlight-indent-guides-method 'character)
(add-hook 'prog-mode-hook 'highlight-indent-guides-mode)

(use-package eglot)

(use-package company)
(global-company-mode 1)
(add-hook 'language-mode-hook #'eglot)

(use-package rust-mode)

(use-package tree-sitter)
(use-package tree-sitter-langs)
(global-tree-sitter-mode)
(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)

(use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook))
(setq dashboard-footer-messages '("Insert phrases here" "like this"))
;(setq dashboard-footer-icon (all-the-icons-octicon "emacs"
;    :height 1.5
;    :v-adjust -0.05
;    :face 'font-lock-keyword-face))

(use-package gruvbox-theme)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;; Keybinds ;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(global-set-key (kbd "<escape>") 'keyboard-escape-quit) ; ESC to escape menus
;;(global-set-key (kbd "<SPC> b") 'counsel-switch-buffer) ; ESC to escape menus

(general-create-definer my-leader-def
  :prefix "SPC")

(my-leader-def
  :keymaps 'normal
  "b" 'counsel-switch-buffer
  "s" 'swiper
  
  "no" 'neotree
  "nf" 'neotree-find
  "nc" 'neotree-hide

  "ls" 'eglot
  "lv" 'eglot-find-declaration
  "ln" 'eglot-rename

  "r" 'eval-buffer)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;; Theming ;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(set-face-attribute 'default nil :font "Iosevka" :height 160) ; Set font
(load-theme 'doom-gruvbox t) ; Set theme

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;; Autogenerated stuff ;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(company neotree use-package treemacs-evil tree-sitter-langs hlinum general doom-themes doom-modeline counsel all-the-icons)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
