#! /bin/sh
#### AUTOSTART ####
# picom &
# nitrogen --restore &

#### MONITORS ####
bspc monitor -d 1 2 3 4 5

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  6
bspc config window_gap                    10
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         false
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


#### BSPWM coloring ####
bspc config normal_border_color     "#fb4934"
bspc config active_border_color     "#fb4934"
bspc config focused_border_color    "#fabd2f"
bspc config presel_feedback_color   "#fabd2f"
